config/routes.rb
Rails.application.routes.draw do
  # Landing page
  root 'intervals/root#index'

  namespace :intervals do
      resources :root, only: [:index, :show, :create, :destroy]
      resources :node, only: [:create, :destroy]
  end
end

app/controllers/intervals/node_controller.rb
class Intervals::NodeController < ApplicationController

  ##
  # Destroy the node and redirect to the tree visualisation
  def destroy
    load_node
    @node.destroy
    redirect_to intervals_root_path(id: @node.root_id),
                success: "Node deleted"
  end


  ##
  # Create a new node inside the tree.
  def create
    unless build_node and save_node
      # TODO add some logic to render error on new tree child we wanted
      # to create.
    end
  end

private

  ##
  # Get the parameter for the node.
  # If the parameters is empty or not exists, return empty array.
  def node_params
    node_params = params[:node]
    node_params ? node_params.permit(:label,
                                     :left_tree,
                                     :right_tree,
                                     :tree_level,
                                     :root_id) : {}
  end

  ##
  # Give the node's scope the controller can working on.
  def node_scope
    Node::AsNode.all
  end

  ##
  # Load a node by the id given in parameter.
  # Raise exception if the id parameter is not given.
  def load_node
    @node ||= node_scope.find(params.require(:id))
  end

  ##
  # Build a node from param, or give a new node if no parameter
  # is given.
  def build_node
    @node ||= node_scope.build.as_node
    @node.attributes = node_params
  end

  ##
  # Save the node and redirect to the tree visualisation.
  def save_node
    @node.save and redirect_to intervals_root_path(@node.root_id)
  end
end

app/controllers/intervals/root_controller.rb
class Intervals::RootController < ApplicationController
  ##
  # Show the tree creation form and the trees already created.
  def index
    build_tree and load_trees
  end

  ##
  # Show the wanted tree.
  #
  # Json serialisation will give the complete tree,
  # ordered by evel and left_tree indice
  def show
    load_tree
     respond_to do |format|
        format.html
        format.json  { render json: {
          root: @tree,
          children: @tree.children.order(tree_level: :asc, left_tree: :asc) } }
      end
  end

  ##
  # destroy the tree, and go back to the root page.
  def destroy
    load_tree
    @tree.destroy
    redirect_to root_path, success: "Tree deleted"
  end

  ##
  # Create a new tree and visualise it.
  # Display errors if data for creation are not valid.
  def create
    unless build_tree and save_tree
      load_trees and render :index
    end
  end

private

  ##
  # Node all the trees disponible.
  def load_trees
    @trees ||= tree_scope
  end

  ##
  # Load the tree wanted by the parameter ´id´.
  # Rais exception if parameter is omited, or root node not found.
  def load_tree
    @tree ||= tree_scope.find(params.require(:id))
  end

  ##
  # Build the tere from the parameter given.
  # If no parameter given, give a new tree.
  def build_tree
    @tree ||= tree_scope.build
    @tree.attributes = tree_params
  end

  ##
  # Save the tree, and redirect to the visualisation of the tree.
  def save_tree
    @tree.save and redirect_to intervals_root_path(@tree.id)
  end

  ##
  # Parameter permitted on manipulating a tree.
  def tree_params
    tree_params = params[:node]
    tree_params ? tree_params.permit(:label) : {}
  end

  ##
  # The scope the controller is working on for tree.
  def tree_scope
    Node::AsRoot.all
  end
end

app/helpers/intervals/tree_helper.rb
module Intervals::TreeHelper
  def callout_class resource, class_if_fine='primary'
    if resource.errors.any?
        'alert'
    else
      class_if_fine
    end
  end

  def display_label_error resource
    render partial: "intervals/root/errors",
           locals: { errors: resource.errors} if resource.errors.any?
  end
end

app/views/intervals/tree/index.html.erb
<div class="callout large <%= callout_class @tree %>">
    <div class="row column text-center">
      <h1>Create a new tree</h1>
      <%= form_for(@tree, url: intervals_tree_index_path(), method: :post) do |form| %>

        <%= form.label :label, "Give your root a name !" %>
        <%= form.text_field :label, placeholder: "Root name", autofocus: true %>
        <input type="hidden" name="as_root" value="1" />
        <%= display_label_error @tree %>
        <button type="submit" class="success button expanded">
          Save
        </button>
      <% end %>
    </div>
</div>
<div class="row">
  <div class="small-12 large-9 large-3-offset columns">
    <h2>Your trees</h2>
    <% @trees.each do |tree| %>
      <%= link_to intervals_tree_path(id: tree.id),
                  class: ["button", "large", "hollow"] do %>
        <%= tree.label %>
      <% end %>
    <% end %>
   </div>
</div>

app/views/intervals/tree/show.html.erb
<div class="row">
  <%= link_to root_path(), class: ["button", "large", "hollow", "secondary"] do %>
    < Back
  <% end %>

  <div class="tree__layout">
    <p class="lead text-right">
      Add and remove node to your tree.
    </p>
    <table class="tree__table">
      <tbody>
        <% (@tree.tree
              .maximum(:tree_level) + 1).times do |level| %>
          <%= render partial: "intervals/tree/show/tree_level",
                     locals:{ collection: @tree.tree.order(left_tree: :asc)
                                    .where(tree_level: level),
                              level: level,
                              max_right_tree: @tree.right_tree } %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>