config/routes.rb
Rails.application.routes.draw do
  # Landing page
  root 'intervals/root#index'

  namespace :intervals do
      resources :root, only: [:index, :show, :create, :destroy]
      resources :node, only: [:create, :destroy]
  end
end

app/controllers/intervals/root_controller.rb
class Intervals::RootController < ApplicationController
  ##
  # Show the tree creation form and the trees already created.
  def index
    build_tree and load_trees
  end

  ##
  # Show the wanted tree.
  #
  # Json serialisation will give the complete tree,
  # ordered by evel and left_tree indice
  def show
    load_tree
     respond_to do |format|
        format.html
        format.json  { render json: {
          root: @tree,
          children: @tree.children.order(tree_level: :asc, left_tree: :asc) } }
      end
  end

  ##
  # destroy the tree, and go back to the root page.
  def destroy
    load_tree
    @tree.destroy
    redirect_to root_path, success: "Tree deleted"
  end

  ##
  # Create a new tree and visualise it.
  # Display errors if data for creation are not valid.
  def create
    unless build_tree and save_tree
      load_trees and render :index
    end
  end

private

  ##
  # Node all the trees disponible.
  def load_trees
    @trees ||= tree_scope
  end

  ##
  # Load the tree wanted by the parameter ´id´.
  # Rais exception if parameter is omited, or root node not found.
  def load_tree
    @tree ||= tree_scope.find(params.require(:id))
  end

  ##
  # Build the tere from the parameter given.
  # If no parameter given, give a new tree.
  def build_tree
    @tree ||= tree_scope.build
    @tree.attributes = tree_params
  end

  ##
  # Save the tree, and redirect to the visualisation of the tree.
  def save_tree
    @tree.save and redirect_to intervals_root_path(@tree.id)
  end

  ##
  # Parameter permitted on manipulating a tree.
  def tree_params
    tree_params = params[:node]
    tree_params ? tree_params.permit(:label) : {}
  end

  ##
  # The scope the controller is working on for tree.
  def tree_scope
    Node::AsRoot.all
  end
end

app/views/intervals/root/show/_node_delete.html.erb
  <%= link_to intervals_node_path(id: node.id),
              method: :delete,
              class: ["tree__delete", "button", "alert", "small"] do %>
    <strong>X</strong>
     Remove <%= if node.leaf?; 'leaf'
        elsif node.root?; 'root'
        else 'node'
        end %>
  <% end %>

app/views/intervals/root/show/_root_delete.html.erb
  <%= link_to intervals_root_path(id: node.id),
              method: :delete,
              class: ["tree__delete", "button", "alert", "small"] do %>
    <strong>X</strong>
     Remove <%= if node.leaf?; 'leaf'
        elsif node.root?; 'root'
        else 'node'
        end %>
  <% end %>

app/views/intervals/root/show/_tree_level.html.erb
<tr class="tree__row">
<% cell_id = 0 %>

<% collection.each do |node| %>
  <% if node.left_tree - cell_id > 1 %>
    <td colspan="<%= node.left_tree - cell_id - 1 %>">
    </td>
  <% end %>

  <td colspan="<%= (node.right_tree - node.left_tree + 1) %>"
      class="tree__cell <%= if node.leaf?; 'leaf'
                            elsif node.root?; 'root'
                            else 'node'
                            end %>">
    <div class="tree__left">
      <%= node.left_tree %>
    </div>
    <div class="tree__right">
      <%= node.right_tree %>
    </div>

    <% if node.root? %>
      <%= render partial: "intervals/root/show/root_delete",
                 locals: {node: node} %>
    <% else %>
      <%= render partial: "intervals/root/show/node_delete",
                 locals: {node: node} %>
    <% end %>

    <div class="tree__label">
      <%= node.label %>
    </div>

    <%= render partial: "intervals/root/show/tree_new_child",
               locals: { node: if node.root?; node.as_root
                               else; node.as_node
                               end}%>
  </td>
  <% cell_id = node.right_tree %>
<% end %>
  <% if max_right_tree - cell_id > 0  %>
  <td colspan="<%=max_right_tree - cell_id %>">
  </td>
  <% end %>
</tr>

app/views/intervals/root/show/_tree_new_child.html.erb
<% resource = node.build_child %>
<%= form_for resource,
             url: intervals_node_index_path(),
             method: :post  do |form| %>
  <div class="form <%= callout_class resource, '' %>">
    <%= form.hidden_field :left_tree %>
    <%= form.hidden_field :right_tree %>
    <%= form.hidden_field :tree_level %>
    <%= form.hidden_field :root_id %>
    <div class="input-group">
      <%= form.text_field :label, placeholder: "Child label", autofocus: false, class: "input-group-field" %>
      <div class="input-group-button">
        <button type="submit" class="button">
          Add
        </button>
      </div>
    </div>
    <%= display_label_error resource%>
  </div>
<% end %>